rootProject.name = "apm"

include(":app:aem:api")
include(":app:aem:runmodes")
include(":app:aem:runmodes.cloud")
include(":app:aem:core")
include(":app:aem:actions.checks")
include(":app:aem:actions.main")
include(":app:aem:ui.apps.base")
include(":app:aem:ui.apps")
include(":app:aem:ui.apps.cloud")
include(":app:aem:ui.system.user")
include(":app:aem:ui.content")
include(":examples")
include(":app:aem:all")
include(":app:aem:all.cloud")